# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0.1+1.21.11
maven_group=dev.jolkert
archives_base_name=name_color
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.141.4+1.21.11
# java version 21
org.gradle.java.home=C:/Program Files/Java/jdk-21
fabric_permission_version=0.6.1